# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MvaRtcc
                                 A QGIS plugin
 Creates MVA and RTCC surfaces from coordinates in CSV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-27
        copyright            : (C) 2024 by Paul Haubourdin
        email                : paul.haubourdin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MvaRtcc class from file MvaRtcc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mva_rtcc import MvaRtcc
    return MvaRtcc(iface)
